language: shell
os: linux
arch: ppc64le
dist: bionic
services:
  - docker

install:
  - sudo apt-get update

script:
  - sudo printf "deb https://oplab9.parqtec.unicamp.br/pub/repository/debian/ ./" >> /etc/apt/sources.list
  - wget https://oplab9.parqtec.unicamp.br/pub/key/openpower-gpgkey-public.asc
  - sudo apt-key add openpower-gpgkey-public.asc
  - sudo apt-get update
  #- sudo apt -y install docker-ce
  - sudo apt -y install conntrack
  - sudo apt-get -y install minikube
  - sudo minikube version
  - systemctl enable docker.service
  - sudo minikube start --driver=none
