language: shell
os: linux
arch: ppc64le
dist: bionic
services:
  - docker

install:
  - sudo apt-get update

script:
  - printf "deb https://oplab9.parqtec.unicamp.br/pub/repository/debian/ ./" >> /etc/apt/sources.list
  - wget https://oplab9.parqtec.unicamp.br/pub/key/openpower-gpgkey-public.asc
  - apt-key add openpower-gpgkey-public.asc
  - apt-get update
  - apt -y install docker-ce
  - apt -y install sudo
  - apt -y install conntrack
  - apt-get -y install minikube
  - minikube version"
  - minikube start --driver=none"
